# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js workers

on:
  workflow_dispatch:
  push:
    branches:
    - src/*
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: node
      - name: install
        run: npm install --save-dev
      - name: build
        run: |
          npm run build:workers
          cp ./dist/index.js worker.js
          cp ./dist/index.js _worker.js
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add worker.js _worker.js
          git commit -m "Automated update" || echo "No changes to commit"
          git push
